/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_nxt_NXTEvent */

#ifndef _Included_lejos_nxt_NXTEvent
#define _Included_lejos_nxt_NXTEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef lejos_nxt_NXTEvent_NONE
#define lejos_nxt_NXTEvent_NONE 0L
#undef lejos_nxt_NXTEvent_BLUETOOTH
#define lejos_nxt_NXTEvent_BLUETOOTH 1L
#undef lejos_nxt_NXTEvent_USB
#define lejos_nxt_NXTEvent_USB 2L
#undef lejos_nxt_NXTEvent_RS485
#define lejos_nxt_NXTEvent_RS485 3L
#undef lejos_nxt_NXTEvent_ANALOG_PORTS
#define lejos_nxt_NXTEvent_ANALOG_PORTS 4L
#undef lejos_nxt_NXTEvent_I2C_PORTS
#define lejos_nxt_NXTEvent_I2C_PORTS 5L
#undef lejos_nxt_NXTEvent_BUTTONS
#define lejos_nxt_NXTEvent_BUTTONS 6L
#undef lejos_nxt_NXTEvent_SYSTEM
#define lejos_nxt_NXTEvent_SYSTEM 7L
#undef lejos_nxt_NXTEvent_WAITING
#define lejos_nxt_NXTEvent_WAITING 1L
#undef lejos_nxt_NXTEvent_SET
#define lejos_nxt_NXTEvent_SET 2L
#undef lejos_nxt_NXTEvent_TIMEOUT
#define lejos_nxt_NXTEvent_TIMEOUT -2147483648L
#undef lejos_nxt_NXTEvent_USER1
#define lejos_nxt_NXTEvent_USER1 536870912L
#undef lejos_nxt_NXTEvent_USER2
#define lejos_nxt_NXTEvent_USER2 268435456L
#undef lejos_nxt_NXTEvent_USER3
#define lejos_nxt_NXTEvent_USER3 134217728L
#undef lejos_nxt_NXTEvent_USER4
#define lejos_nxt_NXTEvent_USER4 67108864L
#undef lejos_nxt_NXTEvent_WAIT_FOREVER
#define lejos_nxt_NXTEvent_WAIT_FOREVER 9223372036854775807i64
/*
 * Class:     lejos_nxt_NXTEvent
 * Method:    registerEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_NXTEvent_registerEvent
  (JNIEnv *, jobject);

/*
 * Class:     lejos_nxt_NXTEvent
 * Method:    unregisterEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_NXTEvent_unregisterEvent
  (JNIEnv *, jobject);

/*
 * Class:     lejos_nxt_NXTEvent
 * Method:    changeEvent
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_NXTEvent_changeEvent
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
