#!/bin/bash

if [ -z "$NXJ_HOME" ]; then 
  NXJ_HOME="$(dirname -- "$NXJ_BIN")"
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NXJ_HOME/bin
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$NXJ_HOME/bin

if [ "$(uname -o)" == "Cygwin" ]; then
	SEP=";"
else
	SEP=":"
fi

THIRDPARTY_LIBS="$NXJ_HOME/3rdparty/lib"

if [ "$(uname -a)" == "Linux" ]; then
	BLUECOVELIBS="$THIRDPARTY_LIBS/bluecove.jar$SEP$THIRDPARTY_LIBS/bluecove-gpl.jar"
else
	BLUECOVELIBS="$THIRDPARTY_LIBS/bluecove.jar"
fi

LEJOS_BOOTPATH="$NXJ_HOME/lib/classes.jar"

LINK_CLASSPATH="$THIRDPARTY_LIBS/bcel-5.1.jar$SEP$THIRDPARTY_LIBS/commons-cli-1.0.jar$SEP$NXJ_HOME/lib/jtools.jar"
TOOL_CLASSPATH="$BLUECOVELIBS$SEP$LINK_CLASSPATH$SEP$NXJ_HOME/lib/pccomm.jar$SEP$NXJ_HOME/lib/pctools.jar"

run_java()
{
	java "$@"
}

run_javac()
{
	javac "$@"
}

run_command()
{
	run_java \
		-DCOMMAND_NAME="$(basename -- "$0")" \
		-Dnxj.home="$NXJ_HOME" \
		-Djava.library.path="$NXJ_HOME/bin" \
		"$@"
}

run_link()
{
	run_command -classpath "$LINK_CLASSPATH" "$@"
}

run_tool()
{
	run_command -classpath "$TOOL_CLASSPATH" "$@"
}
