#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxj: Links and uploads a program to the NXT
#      and optionally runs it
#
# June 7, 2007  created Lawrie Griffiths

run_tool lejos.pc.tools.NXJLinkAndUpload \
	--bootclasspath "$LEJOS_BOOTPATH" \
	--classpath "." \
	--writeorder LE \
	"$@"
