#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxjbrowse: Browses files on the NXT
#
# June 7, 2007  created Lawrie Griffiths

run_tool lejos.pc.tools.NXJBrowser "$@"
