#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjconsoleviewer: GUI Viewer for RConsole output
#

java \
	-DCOMMAND_NAME="$0" \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-classpath "$TOOL_CLASSPATH" \
	lejos.pc.tools.ConsoleViewer \
	"$@"
