#!/bin/bash

#
# nxjcjc: Java tool for compiling java programs for LeJOS NXJ
#
# July 7, 2007  created L. Griffiths

if [ -z "$NXJ_HOME" ]; then
  NXJ_HOME="$(dirname $(dirname $0))"
fi

if [ $OSTYPE == "cygwin" ]; then
  SEP=";"
else
  SEP=":"
fi

javac -source 1.3 -target 1.1 -bootclasspath "$NXJ_HOME\lib\classes.jar$SEP$CLASSPATH" "$@"
