#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjc: Java tool for compiling java programs for leJOS NXJ
#
# July 7, 2007  created Lawrie Griffiths

javac \
	-bootclasspath "$LEJOS_BOOTPATH"\
	"$@"
