#!/bin/bash

#
# nxjflashg: run GUI flash utility
#

if [ -z "$NXJ_HOME" ]; then 
  NXJ_HOME="$(dirname $(dirname $0))"
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NXJ_HOME/bin
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$NXJ_HOME/bin

if [ $OSTYPE == "cygwin" ]; then
  SEP=";"
else
  SEP=":"
fi

java -Djava.library.path="$NXJ_HOME/bin" -Dnxj.home="$NXJ_HOME" -classpath "$NXJ_HOME/lib/pctools.jar$SEP$NXJ_HOME/lib/pccomm.jar" lejos.pc.tools.NXJFlashG "$@"
