#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjupload: Uploads a program or other file to the NXT
#            and optionally runs it
#
# June 1st, 2007  created Lawrie Griffiths

java \
	-DCOMMAND_NAME="$0" \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-classpath "$TOOL_CLASSPATH" \
	lejos.pc.tools.NXJUpload \
	"$@"
