#!/bin/bash

#
# nxjupload: Uploads a program or other file to the NXT
#            and optionally runs it
#
# June 1st, 2007  created L. Griffiths

if [ -z "$NXJ_HOME" ]; then 
  NXJ_HOME="$(dirname $(dirname $0))"
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NXJ_HOME/bin

if [ $OSTYPE == "cygwin" ]; then
  SEP=";"
else
  SEP=":"
fi

THIRDPARTY_LIBS="$NXJ_HOME/3rdparty/lib"

java -Djava.library.path="$NXJ_HOME/bin" -Dnxj.home="$NXJ_HOME" -classpath "$THIRDPARTY_LIBS/bcel-5.1.jar$SEP$THIRDPARTY_LIBS/commons-cli-1.0.jar$SEP$NXJ_HOME/lib/pctools.jar$SEP$NXJ_HOME/lib/pccomm.jar$SEP$NXJ_HOME/lib/jtools.jar$SEP$THIRDPARTY_LIBS/bluecove.jar" lejos.pc.tools.NXJUpload "$@"
