#!/bin/bash

#
# lejosdl: Java tool for downloading and running
# VM java binary using libnxt.
# NXT must be in SAMBA (firmware download) mode.
#
# 08/01/2006  created L. Griffiths

if [ -z "$LEJOS_HOME" ]; then
  LEJOS_HOME="$(dirname $(dirname $0))"
fi

runjava $LEJOS_HOME/bin/lejos_nxt.bin "$@"
