#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjbrowse: Browses files on the NXT
#
# June 7, 2007  created Lawrie Griffiths

java \
	-DCOMMAND_NAME="$0" \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-classpath "$TOOL_CLASSPATH" \
	lejos.pc.tools.NXJBrowser \
	"$@"
