#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxjc: Java tool for compiling java programs for leJOS NXJ
#
# July 7, 2007  created Lawrie Griffiths

run_javac -bootclasspath "$LEJOS_BOOTPATH" "$@"
