#!/bin/bash

#
# nxjc: Java tool for compiling java programs for LeJOS NXJ
#
# July 7, 2007  created L. Griffiths

if [ -z "$NXJ_HOME" ]; then
  NXJ_HOME="$(dirname $(dirname $0))"
fi

if [ $OSTYPE == "cygwin" ]; then
  SEP=";"
else
  SEP=":"
fi

javac -bootclasspath "$NXJ_HOME/lib/classes.jar$SEP$CLASSPATH" "$@"
