#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxjdataviewer: Remote viewer for NXJ Datalogger
#
# Lawrie Griffiths

run_tool lejos.pc.tools.DataViewer "$@"
