#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjflash: Run Java command line flash utility
#
# Andy Shaw

java \
	-DCOMMAND_NAME="$0" \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-classpath "$TOOL_CLASSPATH" \
	lejos.pc.tools.NXJFlash \
	"$@"
