#!/bin/bash

#
# lnxjlink: Java tool to link java programs for LeJOS NXJ
#
# 12/12/02  created L. Griffiths

if [ -z "$NXJ_HOME" ]; then 
  NXJ_HOME="$(dirname $(dirname $0))"
fi

if [ $OSTYPE == "cygwin" ]; then
  SEP=";"
else
  SEP=":"
fi

THIRDPARTY_LIBS="$NXJ_HOME/3rdparty/lib"

if [ `uname` == "Linux" ]; then
  BLUECOVELIBS="$THIRDPARTY_LIBS/bluecove.jar$SEP$THIRDPARTY_LIBS/bluecove-gpl.jar"
else
  BLUECOVELIBS="$THIRDPARTY_LIBS/bluecove.jar"
fi

LINK_CLASSPATH=".$SEP$THIRDPARTY_LIBS/bcel-5.1.jar$SEP$THIRDPARTY_LIBS/commons-cli-1.0.jar$SEP$NXJ_HOME/lib/jtools.jar$SEP$BLUECOVELIBS"

java -DCOMMAND_NAME=nxjlink -classpath "$LINK_CLASSPATH" js.tinyvm.TinyVM --writeorder LE --classpath ".$SEP$NXJ_HOME/lib/classes.jar" "$@"
