#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjlink: Java tool to link java programs for leJOS NXJ
#
# 12/12/02  created Lawrie Griffiths

java \
	-DCOMMAND_NAME="$0" \
	-classpath "$LINK_CLASSPATH" \
	js.tinyvm.TinyVM \
	--bootclasspath "$LEJOS_BOOTPATH" \
	--classpath "." \
	--writeorder LE \
	"$@"
