#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxjlink: Java tool to link java programs for leJOS NXJ
#
# 12/12/02  created Lawrie Griffiths

run_link js.tinyvm.TinyVM \
	--bootclasspath "$LEJOS_BOOTPATH" \
	--classpath "." \
	--writeorder LE \
	"$@"
