#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjpccomm: Run a PC program that uses the PC API. First parameter is trhe main class name.
#

java \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-Xbootclasspath/a:"$TOOL_CLASSPATH" \
	"$@"
