#!/bin/bash
NXJ_BIN="$(dirname -- "$(readlink -f -- "$0")")"
source $NXJ_BIN/_nxjconfig

#
# nxjpccomm: Run a PC program that uses the PC API. First parameter is trhe main class name.
#

run_java \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-Xbootclasspath/a:"$TOOL_CLASSPATH" \
	"$@"
