#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjsocketproxy: Socket Proxy for leJOS NXJ
#
# Lawrie Griffiths

java \
	-DCOMMAND_NAME="$0" \
	-Dnxj.home="$NXJ_HOME" \
	-Djava.library.path="$NXJ_HOME/bin" \
	-classpath "$TOOL_CLASSPATH" \
	lejos.pc.tools.SocketProxy
	"$@"
