#!/bin/bash
source "$(dirname -- "$0")"/_nxjconfig

#
# nxjupload: Uploads a program or other file to the NXT
#            and optionally runs it
#
# June 1st, 2007  created Lawrie Griffiths

run_tool lejos.pc.tools.NXJUpload "$@"
