/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nxjplugincode;

import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//nxjplugincode//NXJTools//EN",
autostore = false)
@TopComponent.Description(preferredID = "NXJToolsTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "nxjplugincode.NXJToolsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_NXJToolsAction",
preferredID = "NXJToolsTopComponent")
public final class NXJToolsTopComponent extends TopComponent
{

   public NXJToolsTopComponent()
   {
      initComponents();
      setName(NbBundle.getMessage(NXJToolsTopComponent.class, "CTL_NXJToolsTopComponent"));
      setToolTipText(NbBundle.getMessage(NXJToolsTopComponent.class, "HINT_NXJToolsTopComponent"));

   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      controlPanel1 = new nxjplugincode.ControlPanel();

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(controlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(controlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(23, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private nxjplugincode.ControlPanel controlPanel1;
   // End of variables declaration//GEN-END:variables
   @Override
   public void componentOpened()
   {
      // TODO add custom code on component opening
   }

   @Override
   public void componentClosed()
   {
      // TODO add custom code on component closing
   }

   void writeProperties(java.util.Properties p)
   {
      // better to version settings since initial version as advocated at
      // http://wiki.apidesign.org/wiki/PropertyFiles
      p.setProperty("version", "1.0");
      // TODO store your settings
   }

   void readProperties(java.util.Properties p)
   {
      String version = p.getProperty("version");
      // TODO read your settings according to their version
   }
}
