/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_nxt_SensorPort */

#ifndef _Included_lejos_nxt_SensorPort
#define _Included_lejos_nxt_SensorPort
#ifdef __cplusplus
extern "C" {
#endif
#undef lejos_nxt_SensorPort_POWER_STD
#define lejos_nxt_SensorPort_POWER_STD 0L
#undef lejos_nxt_SensorPort_POWER_RCX9V
#define lejos_nxt_SensorPort_POWER_RCX9V 1L
#undef lejos_nxt_SensorPort_POWER_9V
#define lejos_nxt_SensorPort_POWER_9V 2L
#undef lejos_nxt_SensorPort_SP_DIGI0
#define lejos_nxt_SensorPort_SP_DIGI0 0L
#undef lejos_nxt_SensorPort_SP_DIGI1
#define lejos_nxt_SensorPort_SP_DIGI1 1L
#undef lejos_nxt_SensorPort_SP_ANA
#define lejos_nxt_SensorPort_SP_ANA 2L
#undef lejos_nxt_SensorPort_SP_MODE_OFF
#define lejos_nxt_SensorPort_SP_MODE_OFF 0L
#undef lejos_nxt_SensorPort_SP_MODE_INPUT
#define lejos_nxt_SensorPort_SP_MODE_INPUT 1L
#undef lejos_nxt_SensorPort_SP_MODE_OUTPUT
#define lejos_nxt_SensorPort_SP_MODE_OUTPUT 2L
#undef lejos_nxt_SensorPort_SP_MODE_ADC
#define lejos_nxt_SensorPort_SP_MODE_ADC 3L
#undef lejos_nxt_SensorPort_NUMBER_OF_PORTS
#define lejos_nxt_SensorPort_NUMBER_OF_PORTS 4L
#undef lejos_nxt_SensorPort_I2C_IO_COMPLETE
#define lejos_nxt_SensorPort_I2C_IO_COMPLETE 1L
#undef lejos_nxt_SensorPort_I2C_BUS_FREE
#define lejos_nxt_SensorPort_I2C_BUS_FREE 256L
#undef lejos_nxt_SensorPort_I2C_BUS_FREE_TIMEOUT
#define lejos_nxt_SensorPort_I2C_BUS_FREE_TIMEOUT 10L
#undef lejos_nxt_SensorPort_GT_EVENT_SHIFT
#define lejos_nxt_SensorPort_GT_EVENT_SHIFT 0L
#undef lejos_nxt_SensorPort_LT_EVENT_SHIFT
#define lejos_nxt_SensorPort_LT_EVENT_SHIFT 4L
#undef lejos_nxt_SensorPort_TARGET_SHIFT
#define lejos_nxt_SensorPort_TARGET_SHIFT 8L
#undef lejos_nxt_SensorPort_TARGET_MASK
#define lejos_nxt_SensorPort_TARGET_MASK 261888L
#undef lejos_nxt_SensorPort_TOLERANCE_SHIFT
#define lejos_nxt_SensorPort_TOLERANCE_SHIFT 18L
#undef lejos_nxt_SensorPort_TOLERANCE_MASK
#define lejos_nxt_SensorPort_TOLERANCE_MASK 66846720L
#undef lejos_nxt_SensorPort_DEFAULT_TOLERANCE
#define lejos_nxt_SensorPort_DEFAULT_TOLERANCE 2L
/*
 * Class:     lejos_nxt_SensorPort
 * Method:    readSensorValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_readSensorValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    setPowerTypeById
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_lejos_nxt_SensorPort_setPowerTypeById
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    i2cEnableById
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_lejos_nxt_SensorPort_i2cEnableById
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    i2cDisableById
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_lejos_nxt_SensorPort_i2cDisableById
  (JNIEnv *, jclass, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    i2cStatusById
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_i2cStatusById
  (JNIEnv *, jclass, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    i2cStartById
 * Signature: (II[BIII)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_i2cStartById
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    i2cCompleteById
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_i2cCompleteById
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    setSensorPinMode
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_lejos_nxt_SensorPort_setSensorPinMode
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    setSensorPin
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_lejos_nxt_SensorPort_setSensorPin
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    getSensorPin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_getSensorPin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     lejos_nxt_SensorPort
 * Method:    readSensorPin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_SensorPort_readSensorPin
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
