/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_nxt_SensorPort_StandardReader */

#ifndef _Included_lejos_nxt_SensorPort_StandardReader
#define _Included_lejos_nxt_SensorPort_StandardReader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
