/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_nxt_SensorPort_ColorSensorReader */

#ifndef _Included_lejos_nxt_SensorPort_ColorSensorReader
#define _Included_lejos_nxt_SensorPort_ColorSensorReader
#ifdef __cplusplus
extern "C" {
#endif
#undef lejos_nxt_SensorPort_ColorSensorReader_CLOCK
#define lejos_nxt_SensorPort_ColorSensorReader_CLOCK 0L
#undef lejos_nxt_SensorPort_ColorSensorReader_DATA
#define lejos_nxt_SensorPort_ColorSensorReader_DATA 1L
#undef lejos_nxt_SensorPort_ColorSensorReader_ADVOLTS
#define lejos_nxt_SensorPort_ColorSensorReader_ADVOLTS 3300L
#undef lejos_nxt_SensorPort_ColorSensorReader_ADMAX
#define lejos_nxt_SensorPort_ColorSensorReader_ADMAX 1023L
#undef lejos_nxt_SensorPort_ColorSensorReader_MINBLANKVAL
#define lejos_nxt_SensorPort_ColorSensorReader_MINBLANKVAL 71L
#undef lejos_nxt_SensorPort_ColorSensorReader_SENSORMAX
#define lejos_nxt_SensorPort_ColorSensorReader_SENSORMAX 1023L
#ifdef __cplusplus
}
#endif
#endif
