package lejos.robotics.pathfinding;

import java.util.ArrayList;
import java.util.Collection;

import lejos.robotics.navigation.WayPoint;

/**
 * This class represents a Node which can be connected to other neighboring nodes. Node sets can be searched using
 * search algorithms. Typically the search algorithm only requires one starting node and one goal node. It assumes these
 * nodes are linked by intermediate nodes.
 * @author BB
 * @see lejos.robotics.pathfinding.SearchAlgorithm
 */
public class Node  {
	
	/**
	 * The x coordinate of this node.
	 */
	public float x;
	
	/**
	 * The y coordinate of this node.
	 */
	public float y;
	
	private float h_score = 0;
	private float g_score = 0;
	private Node cameFrom = null;
	private ArrayList <Node> neighbors = new ArrayList<Node>();
	
	/**
	 * Creates a new instance of a node.
	 * @param x The x coordinate of this node.
	 * @param y The y coordinate of this node.
	 */
	public Node(float x, float y) {
		this.x = x; 
		this.y = y;
	}
	
	/**
	 * Returns all the neighbors which this node is connected to. 
	 * @return The collection of all neighboring nodes.
	 */
	public Collection <Node> getNeighbors() {
		return neighbors;
	}
	
	/**
	 * Indicates the number of neighbors (nodes connected to this node).
	 * @return int Number of neighbors.
	 */
	public int neighbors() {
		return neighbors.size();
	}
	
	/**
	 * Adds a neighboring node to this node, connecting them together. Note: You must make sure to add this node
	 * to the neighbor, and also add the neighbor to this node. This method doesn't do both.
	 * @param neighbor The neighboring node to connect with.
	 * @return Returns false if the neighbor already existed, or if you try to add this node to itself as a neighbor.
	 */
	public boolean addNeighbor(Node neighbor) {
		// TODO: OPTION - Maybe code here should add each other as neighbors?
		// Check to make sure same isn't added twice. (Assuming ArrayList doesn't do this already?)
		if(neighbors.contains(neighbor)) return false;
		// Check to make sure doesn't add itself
		if(neighbor == this) return false;
		neighbors.add(neighbor);
		return true;
	}
	
	/**
	 * Removes a node from this node as neighbors, effectively disconnecting them. Note: You have to remove
	 * this node from the neighbor, and also remove the neighbor from this node. This method doesn't do both.	
	 * @param neighbor The neighboring node to disconnect from.
	 * @return Returns false if the neighbor did not previously exist as a neighbor.
	 */
	public boolean removeNeighbor(Node neighbor) {
		// TODO: Maybe code here should remove each other as neighbors?
		return neighbors.remove(neighbor);
	}
	
	/**
	 * Method used by A* to calculate search score.
	 * @param h
	 */
	protected void setH_Score(float h) {
		h_score = h;
	}
	
	/**
	 * Method used by A* to calculate search score.
	 * @param g
	 */
	protected void setG_Score(float g) {
		g_score = g;
	}
	
	/**
	 * Method used by A* to calculate search score.
	 * @return the search score
	 */
	protected float getG_Score(){
		return g_score;
	}
		
	/**
	 * Method used by A* to calculate search score. You can't set FScore because it is 
	 * generated by adding the gscore and hscore.
	 */
	protected float getF_Score(){
		return g_score + h_score;
	}
	
	/**
	 * Used by A* search. Stores the node that the search came from prior to this node. 
	 * @return the predecessor node
	 */
	protected Node getPredecessor() {
		return cameFrom;
	}
	
	/**
	 * Used by A* search. Stores the node that the search came from prior to this node.
	 * @param orig
	 */
	protected void setPredecessor(Node orig) {
		cameFrom = orig;
	}
	 
	// TODO: Move this somewhere else appropriate? Unique to A*.
	protected static void reconstructPath(Node current_node, Node start, Collection <WayPoint> path){
		if(current_node == start) {
			path.add(new WayPoint(current_node.x, current_node.y));
			return; 
		} else reconstructPath(current_node.getPredecessor(), start, path);
		path.add(new WayPoint(current_node.x, current_node.y));
		return;
	}

}