
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import lejos.pc.tools.*;
   
/**
 * GUI application for reot control of a NXT running RCNavigator<br>
 * Units of distance:  feet
 * @author  Roger
 */
public class RCNavigationControl extends javax.swing.JFrame
{

   /** Creates new form RCNavigationControl */
   public RCNavigationControl()
    {
      initComponents();
    }
   /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
                new RCNavigationControl().setVisible(true);
      
    }
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      connectButton = new javax.swing.JButton();
      nameF = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      robotPanel = new javax.swing.JPanel();
      jLabel7 = new javax.swing.JLabel();
      robotX = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      robotY = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      robotHeading = new javax.swing.JTextField();
      commandPanel = new javax.swing.JPanel();
      rotateButton = new javax.swing.JButton();
      jLabel5 = new javax.swing.JLabel();
      angleField = new javax.swing.JTextField();
      travelButton = new javax.swing.JButton();
      jLabel4 = new javax.swing.JLabel();
      distanceField = new javax.swing.JTextField();
      goButton = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      XField = new javax.swing.JTextField();
      YField = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("RC Navigator Control");

      connectButton.setText("Connect");
      connectButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            connectButtonMouseClicked(evt);
         }
      });

      jLabel1.setText("NXT name or address");

      robotPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Robot Position and Heading"));

      jLabel7.setText("X ");

      robotX.setText(" ");

      jLabel8.setText("Y");

      jLabel9.setText("Heading");

      robotHeading.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            robotHeadingActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout robotPanelLayout = new javax.swing.GroupLayout(robotPanel);
      robotPanel.setLayout(robotPanelLayout);
      robotPanelLayout.setHorizontalGroup(
         robotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(robotPanelLayout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(robotX, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(robotY, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(robotHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(109, 109, 109))
      );
      robotPanelLayout.setVerticalGroup(
         robotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(robotPanelLayout.createSequentialGroup()
            .addGroup(robotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(robotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(robotX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel7))
               .addGroup(robotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel8)
                  .addComponent(robotY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel9)
                  .addComponent(robotHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(20, Short.MAX_VALUE))
      );

      commandPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Commands"));

      rotateButton.setText("Rotate");
      rotateButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            rotateButtonMouseClicked(evt);
         }
      });

      jLabel5.setText("Angle");

      travelButton.setText("Travel");
      travelButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            travelButtonMouseClicked(evt);
         }
      });

      jLabel4.setText("Distance ");

      goButton.setText("GoTo XY");
      goButton.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            goButtonMouseClicked(evt);
         }
      });

      jLabel2.setText("X");

      jLabel3.setText("Y");

      javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
      commandPanel.setLayout(commandPanelLayout);
      commandPanelLayout.setHorizontalGroup(
         commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(commandPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(rotateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
               .addComponent(travelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
               .addComponent(goButton))
            .addGap(18, 18, 18)
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(9, 9, 9)
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(XField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
               .addComponent(distanceField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
               .addComponent(angleField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(126, 126, 126))
      );
      commandPanelLayout.setVerticalGroup(
         commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(goButton)
               .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel2)
                  .addComponent(XField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel3)
                  .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(travelButton)
               .addComponent(jLabel4)
               .addComponent(distanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(rotateButton)
               .addComponent(jLabel5)
               .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(40, 40, 40)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(28, 28, 28)
                  .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                  .addGap(23, 23, 23))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel6)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(robotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(connectButton)
               .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(83, 83, 83)
                  .addComponent(jLabel6))
               .addGroup(layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(robotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

private void robotHeadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotHeadingActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_robotHeadingActionPerformed

private void connectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButtonMouseClicked
   String NXT = nameF.getText();
   con.startConnector(NXT, false);
   dataIn = con.getDataIn();
   dataOut = con.getDataOut();
   if (dataIn != null)
      System.out.println(" data In  OK");
   else
      System.out.println(" dataIn NULL");
   if (!reader.isRunning)
      reader.start();
}//GEN-LAST:event_connectButtonMouseClicked

private void goButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goButtonMouseClicked
   float x = Float.parseFloat(XField.getText());
   float y = Float.parseFloat(YField.getText());
   send(0, x, y);// TODO add your handling code here:
}//GEN-LAST:event_goButtonMouseClicked

private void travelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_travelButtonMouseClicked
   float distance = Float.parseFloat(distanceField.getText());
   send(1, distance, 0);
}//GEN-LAST:event_travelButtonMouseClicked

private void rotateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotateButtonMouseClicked
   float angle = Float.parseFloat(angleField.getText());
   send(2, angle, 0);
}//GEN-LAST:event_rotateButtonMouseClicked


   class Reader extends Thread
   {

      public boolean reading = false;
      int count = 0;
      boolean isRunning = false;
      public void run()
       {
         isRunning = true;
         while (isRunning)
         {
            if (reading)
            {
               float x = 0;
               float y = 0;
               float h = 0;
               boolean ok = false;
               System.out.print(" reading stream ");
               if (dataIn == null)
                  System.out.println(" dataIn vanished");
               try
               {
                  x = dataIn.readFloat();
                  y = dataIn.readFloat();
                  h = dataIn.readFloat();
                  ok = true;
               } catch (IOException e)
               {
                  System.out.println("can't read");
                  count++;
                  isRunning = count<50;// give up 
                  ok = false;
               }
               if (ok)
               {
                  robotX.setText(Float.toString(x/100));
                  robotY.setText(Float.toString(y/100));
                  robotHeading.setText(Float.toString(h));
                  reading = false;
               }
               Thread.yield();
            }// if reading
         }//while is running
        
       }
   }
      public void send(int code,float xx, float yy)
   {
        System.out.println(" sent "+code+" "+xx+" "+yy);
      try 
      {
         dataOut.writeInt(code);    
         if(code == 0)
         {
            dataOut.writeFloat(100*xx);// Robot uses cm 
            dataOut.writeFloat(100*yy);         
         }
         else if(code == 1) dataOut.writeFloat(100*xx);                          
         else if(code == 2)dataOut.writeFloat(xx);
         dataOut.flush();
      }
      catch(IOException e) {System.out.println("send problem "+e);}
      reader.reading = true;
      }
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField XField;
   private javax.swing.JTextField YField;
   private javax.swing.JTextField angleField;
   private javax.swing.JPanel commandPanel;
   private javax.swing.JButton connectButton;
   private javax.swing.JTextField distanceField;
   private javax.swing.JButton goButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JTextField nameF;
   private javax.swing.JTextField robotHeading;
   private javax.swing.JPanel robotPanel;
   private javax.swing.JTextField robotX;
   private javax.swing.JTextField robotY;
   private javax.swing.JButton rotateButton;
   private javax.swing.JButton travelButton;
   // End of variables declaration//GEN-END:variables
  private Connector con = new Connector();
   /**
    * used by reader
    */
   private DataInputStream dataIn;
   /**
    * used by send()
    */
   private DataOutputStream dataOut;
/*
   * input field for robot name or address
   */
   private Reader reader = new Reader();
   
   
}
