/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_pc_comm_NXTCommLibnxt */

#ifndef _Included_lejos_pc_comm_NXTCommLibnxt
#define _Included_lejos_pc_comm_NXTCommLibnxt
#ifdef __cplusplus
extern "C" {
#endif
#undef lejos_pc_comm_NXTCommLibnxt_USB_BUFSZ
#define lejos_pc_comm_NXTCommLibnxt_USB_BUFSZ 64L
/*
 * Class:     lejos_pc_comm_NXTCommLibnxt
 * Method:    jlibnxt_find
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_lejos_pc_comm_NXTCommLibnxt_jlibnxt_1find
  (JNIEnv *, jobject);

/*
 * Class:     lejos_pc_comm_NXTCommLibnxt
 * Method:    jlibnxt_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_lejos_pc_comm_NXTCommLibnxt_jlibnxt_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     lejos_pc_comm_NXTCommLibnxt
 * Method:    jlibnxt_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lejos_pc_comm_NXTCommLibnxt_jlibnxt_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lejos_pc_comm_NXTCommLibnxt
 * Method:    jlibnxt_send_data
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_lejos_pc_comm_NXTCommLibnxt_jlibnxt_1send_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     lejos_pc_comm_NXTCommLibnxt
 * Method:    jlibnxt_read_data
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_lejos_pc_comm_NXTCommLibnxt_jlibnxt_1read_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
