/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_pc_comm_NXTCommFantom */

#ifndef _Included_lejos_pc_comm_NXTCommFantom
#define _Included_lejos_pc_comm_NXTCommFantom
#ifdef __cplusplus
extern "C" {
#endif
#undef lejos_pc_comm_NXTCommFantom_USB_BUFSZ
#define lejos_pc_comm_NXTCommFantom_USB_BUFSZ 64L
#undef lejos_pc_comm_NXTCommFantom_MIN_TIMEOUT
#define lejos_pc_comm_NXTCommFantom_MIN_TIMEOUT 5000L
#undef lejos_pc_comm_NXTCommFantom_MAX_ERRORS
#define lejos_pc_comm_NXTCommFantom_MAX_ERRORS 10L
/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_find
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1find
  (JNIEnv *, jobject);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_send_data
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1send_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_read_data
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1read_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
