/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_nxt_RPiI2c */

#ifndef _Included_lejos_nxt_RPiI2c
#define _Included_lejos_nxt_RPiI2c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lejos_nxt_RPiI2c
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_RPiI2c_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     lejos_nxt_RPiI2c
 * Method:    read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_RPiI2c_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     lejos_nxt_RPiI2c
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_RPiI2c_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     lejos_nxt_RPiI2c
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lejos_nxt_RPiI2c_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
