package lejos.pc.tools;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.ParseException;

/**
 * Downloads  data from the RConsole running on a NXT <br>
 * Uses USB by default, or Bluetooth  if selected from buttons.
 * If using Bluetooth, you can get a quicker connection entering the name or address
 * of you NXT.<br>
 * Do NOT click "connect" unless the NXT displays the correct "Console" message.
 * status field shows messages
 *
 * @author Roger Glassey 6.1.2008
 *
 */
public class NXJConsoleViewer extends JFrame implements ActionListener, ChangeListener
{
	private class ConsoleUI implements ConsoleViewerUI
	{
		private static final int BUFSIZE = 4096;
		private char[] buf = new char[BUFSIZE];
		private int buflen;
		
	    /**
	     * Messages generated by ConsoleViewComms show in the status Field
	     */
	    public void setStatus(final String s)
	    {
	    	SwingUtilities.invokeLater(new Runnable()
				{
					public void run()
					{
				        statusField.setText(s);
					}
				});
	    }
	    
	    public void connectedTo(final String name, final String address)
	    {
	    	SwingUtilities.invokeLater(new Runnable()
			{
				public void run()
				{
			        nameField.setText(name);
			        addrField.setText(address);
			        statusField.setText("Connected to " + name);
				}
			});
	    }

	    /**
	     * Append data to the log display
	     */
	    public void append(String data)
	    {
    		try
			{
		    	int len = data.length();
		    	for (int i=0; i<len;)
		    	{
		    		i += this.safeAppend(data, i);
		    	}	    	
			}
			catch (InterruptedException e)
			{
				throw new RuntimeException(e);
			}
	    }
	    
	    private synchronized int safeAppend(String s, int off) throws InterruptedException
	    {
	    	int rem;
	    	while (true)
	    	{
	    		rem = BUFSIZE - buflen;
		    	if (rem > 0)
		    		break;
		    	
		    	this.wait();
	    	}
	    	
	    	int len = s.length() - off;
	    	if (len <= 0)
	    		return 0;
	    	if (len > rem)
	    		len = rem;
	    	
	    	int oldlen = buflen;
	    	s.getChars(off, off+len, buf, buflen);
	    	buflen += len;
	    	
	    	if (oldlen == 0)
	    	{
	    		SwingUtilities.invokeLater(new Runnable()
					{
						public void run()
						{
							swingFlushBuffer();
						}
					});
	    	}
	    	
	    	return len;
	    }
	    
	    public synchronized void swingFlushBuffer()
	    {
	    	// method only invoked from swing thread
	    	String s = new String(buf, 0, buflen);
	    	NXJConsoleViewer.this.append(s);
	        buflen = 0;
	        this.notifyAll();
	    }

	    public void updateLCD(final byte[] buffer)
	    {
	    	SwingUtilities.invokeLater(new Runnable()
			{
				public void run()
				{
			        lcd.update(buffer);
				}
			});
	    }

		/**
		 * Log a progress message
		 */
		public void logMessage(String msg) {
			System.out.println(msg);
		}
	}

    private static final int LCD_WIDTH = 100;
    private static final int LCD_HEIGHT = 64;


    private static final long serialVersionUID = -4789857573625988062L;
    private JButton connectButton = new JButton("Connect");
    private JRadioButton usbButton = new JRadioButton("USB");
    private JRadioButton btButton = new JRadioButton("BlueTooth");

    private JLabel statusField = new JLabel();

    private JTextField nameField = new JTextField(10);
    private JTextField addrField = new JTextField(12);
    private ConsoleViewComms comm;
    private boolean usbSelected = true;
    private static final String USING_USB = "Using USB";
    private static final String USING_BT = "Using Bluetooth";
    /**
     * Screen area to hold the downloaded data
     */
    private JTextArea theLog;

    private LCDDisplay lcd;


    class LCDDisplay extends JPanel
    {
        private BufferedImage lcd = new BufferedImage(LCD_WIDTH, LCD_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        private Graphics2D lcdGC = lcd.createGraphics();

        public void paint(Graphics g)
        {
            Graphics2D g2d = (Graphics2D)g;
            super.paint(g);
            int width = getWidth();
            int height = getHeight();
            int imgWidth = lcd.getWidth();
            int imgHeight = lcd.getHeight();
            // Draw a scaled version of the display, keep the aspect ratio and
            // centre it.
            if (width < (height*imgWidth)/imgHeight)
            {
                imgHeight = (width*imgHeight)/imgWidth;
                imgWidth = width;
            }
            else
            {
                imgWidth = (height*imgWidth)/imgHeight;
                imgHeight = height;
            }
            g2d.drawImage(lcd, (width-imgWidth)/2, (height-imgHeight)/2, imgWidth, imgHeight, null);

        }

        public void update(byte [] buffer)
        {
            int offset = 0;
            int row = 0;
            lcdGC.setColor(new Color(255, 255,255, 255));
            lcdGC.fillRect(0, 0, lcd.getWidth(), lcd.getHeight());
            lcdGC.setColor(new Color(0, 128, 0, 100));
            lcdGC.fillRect(0, 0, lcd.getWidth(), lcd.getHeight());
            lcdGC.setColor(new Color(0, 0, 0, 255));
            for(row = 0; row < 64; row += 8)
                for(int x = 0; x < LCD_WIDTH; x++)
                {
                    byte vals = buffer[offset++];
                    for(int y = 0; y < 8; y++)
                    {
                        if ((vals & 1) != 0)
                            lcdGC.fillRect(x, y+row, 1, 1);
                        vals >>= 1;
                    }
                }
            this.repaint();
        }

    }

    /**
     * Constructor builds GUI
     * @param debugFile File containing debug information.
     * @throws IOException 
     */
    public NXJConsoleViewer(String debugFile) throws IOException
    {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("View RConsole output from NXT");

        setSize(680, 600);

        statusField.setPreferredSize(new Dimension(200,20));

        buildGui();
        final ConsoleUI ui = new ConsoleUI();
        ConsoleDebugDisplay debug = new ConsoleDebugDisplay(ui, debugFile);
        comm = new ConsoleViewComms(ui, debug, true, true);
    }

    public void append(String s)
	{
        theLog.append(s);
        theLog.setCaretPosition(theLog.getDocument().getLength());
	}

	public void buildGui()
    {
        JPanel connectPanel = new JPanel();  //holds  button and text field
        ButtonGroup choiceGroup = new ButtonGroup();
        choiceGroup.add(usbButton);
        usbButton.setSelected(true);
        usbButton.addChangeListener(this);
        btButton.addChangeListener(this);
        choiceGroup.add(btButton);
        connectPanel.add(usbButton);
        connectPanel.add(btButton);
        connectPanel.add(new JLabel(" Name"));
        connectPanel.add(nameField);
        connectButton.addActionListener(this);
        connectPanel.add(new JLabel("Addr"));
        connectPanel.add(addrField);

        JPanel statusPanel = new JPanel(new BorderLayout());//  holds label and text field
        statusPanel.add(new JLabel("Status: "), BorderLayout.LINE_START);
        statusPanel.add(statusField, BorderLayout.CENTER);

        JPanel topLeftPanel = new JPanel();  // North area of the frame
        topLeftPanel.setLayout(new GridLayout(2, 1));
        topLeftPanel.add(connectPanel);
        topLeftPanel.add(connectButton);
        lcd = new LCDDisplay();
        //screen.add(new JLabel("Screen"));
        lcd.setMinimumSize(new Dimension(LCD_WIDTH*2, LCD_HEIGHT*2));
        lcd.setEnabled(true);
        lcd.setPreferredSize(lcd.getMinimumSize());
        JPanel topPanel = new JPanel();
        //topPanel.setLayout(new GridLayout(1, 2));
        topPanel.add(topLeftPanel);
        topPanel.add(lcd);
        add(topPanel, BorderLayout.NORTH);
        theLog = new JTextArea(40, 40); // Center area of the frame
        add(new JScrollPane(theLog), BorderLayout.CENTER);

        add(statusPanel, BorderLayout.SOUTH);

        statusField.setText(USING_USB);

    }

    /**
     * Required by action listener. Used by Connect button
     */
    public void actionPerformed(ActionEvent e)
    {
        if (e.getSource() == connectButton)
        {
        	statusField.setText("Connecting");
            theLog.setText("");
            String name = nameField.getText();
            String address = addrField.getText();
            boolean _useUSB = usbButton.isSelected();
            if (!comm.connectTo(name, address, _useUSB))
            {
            	statusField.setText("Connection Failed");
                if (_useUSB)
                {
                    JOptionPane.showMessageDialog(this, "Sorry... USB did not connect.\n" +
                            "You might want to check:\n " +
                            " Is the NXT turned on and connected? \n " +
                            " Does it display  'USB Console...'? ", "We have a connection problem.",
                            JOptionPane.PLAIN_MESSAGE);
                } else
                {
                    JOptionPane.showMessageDialog(this, "Sorry... Bluetooth did not connect. \n" +
                            "You might want to check:\n" +
                            " Is the dongle plugged in?\n" +
                            " Is the NXT turned on?\n" +
                            " Does it display  'BT Console....'? ",
                            "We have a connection problem.",
                            JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
    }

    /**
     * Initialize the display Frame <br>
     */
    public static void main(String[] args)
    {
    	ToolStarter.startSwingTool(NXJConsoleViewer.class, args);
    }
    
    public static int start(String[] args) throws IOException
    {
        ConsoleViewerCommandLineParser fParser = new ConsoleViewerCommandLineParser(NXJConsoleViewer.class, "[options]");
    	CommandLine commandLine;
		try
		{
            commandLine = fParser.parse(args);
		}
		catch (ParseException e)
		{
			fParser.printHelp(System.err, e);
			return 1;
		}
		
		if (commandLine.hasOption("h"))
		{
			fParser.printHelp(System.out);
			return 0;
		}
		
        String debugFile = AbstractCommandLineParser.getLastOptVal(commandLine, "di");
        NXJConsoleViewer frame = new NXJConsoleViewer(debugFile);
        frame.setVisible(true);        
        return 0;
    }

    /**
     * Update the status field when USB or Bluetooth radio buttons selected
     */
	public void stateChanged(ChangeEvent e) {
		if (usbSelected && usbButton.isSelected()) return;
		if (usbButton.isSelected())
		{
			statusField.setText(USING_USB);
			usbSelected = true;
		}
		else 
		{
			statusField.setText(USING_BT);
			usbSelected = false;
		}
	}

}


