/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlPanel.java
 *
 * Created on May 30, 2011, 10:17:51 AM
 */
package nxjplugincode;

            

/**
 *
 * @author owner.GLASSEY
 */
public class ControlPanel extends javax.swing.JPanel
{

   /** Creates new form ControlPanel */
   public ControlPanel()
   {
      initComponents();
      
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      flashB = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      browserB = new javax.swing.JButton();
      consoleB = new javax.swing.JButton();
      dataB = new javax.swing.JButton();

      flashB.setText("Flash  Firmware");
      flashB.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            flashBActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
      jLabel1.setText("    NXJ Tools");

      browserB.setText("NXJ Browser");
      browserB.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            browserBActionPerformed(evt);
         }
      });

      consoleB.setText("Console Viewer");
      consoleB.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            consoleBActionPerformed(evt);
         }
      });

      dataB.setText("Data Viewer");
      dataB.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            dataBActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(flashB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(browserB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(consoleB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(dataB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(browserB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(consoleB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dataB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(flashB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void flashBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_flashBActionPerformed
   {//GEN-HEADEREND:event_flashBActionPerformed
      cp.process("nxjflashg.bat")   ;
}//GEN-LAST:event_flashBActionPerformed

   private void browserBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browserBActionPerformed
   {//GEN-HEADEREND:event_browserBActionPerformed
      cp.process("nxjbrowse.bat");
}//GEN-LAST:event_browserBActionPerformed

   private void consoleBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consoleBActionPerformed
   {//GEN-HEADEREND:event_consoleBActionPerformed
     cp. process("nxjConsoleViewer.bat");
}//GEN-LAST:event_consoleBActionPerformed

   private void dataBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dataBActionPerformed
   {//GEN-HEADEREND:event_dataBActionPerformed
      cp. process("nxjDataViewer.bat");
}//GEN-LAST:event_dataBActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton browserB;
   private javax.swing.JButton consoleB;
   private javax.swing.JButton dataB;
   private javax.swing.JButton flashB;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
   BatExec cp = new BatExec();
}
  
   class BatExec
{

   public void  process(String batFile)
   {
      cmd[2] = "cd %nxj_home%&&" + batFile;
      Runtime rt = Runtime.getRuntime();
      try
      {
         Process process = rt.exec(cmd);
      } catch (Exception e)
      {
         System.out.println(e);
      }
   }
   private static String[] cmd ={"cmd", "/c", " cd %nxj_home%&&nxjconsoleviewer.bat"};
}

