/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lejos_pc_comm_NXTCommFantom */

#ifndef _Included_lejos_pc_comm_NXTCommFantom
#define _Included_lejos_pc_comm_NXTCommFantom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_find
 * Signature: ()I
 */
JNIEXPORT jobjectArray JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1find
  (JNIEnv *, jobject);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_send_data
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1send_1data
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     lejos_pc_comm_NXTCommFantom
 * Method:    jfantom_read_data
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_lejos_pc_comm_NXTCommFantom_jfantom_1read_1data
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
