package lejos.robotics;

/*
 * WARNING: THIS CLASS IS SHARED BETWEEN THE classes AND pccomms PROJECTS.
 * DO NOT EDIT THE VERSION IN pccomms AS IT WILL BE OVERWRITTEN WHEN THE PROJECT IS BUILT.
 */

/**
 * An event generated by a TachoMotor. The event represents a change in the movement of the motor.
 * Tachometer reading is the only data recorded at the time of the event. MotorEvent also contains 
 * an instance of the TachoMotor responsible for the event. 
 */
public class MotorEvent {
	
	private TachoMotor motor;
	private int tacho;
	
	public MotorEvent(TachoMotor motor, int tachoCount) {
		this.motor = motor;
		this.tacho = tachoCount;
	}
	
	/**
	 * Provides a "frozen in time" reading of the tachometer at the time the event occurred.
	 * @return
	 */
	public int getTachoCount() {
		return this.tacho;
	}
	
	/**
	 * Provides a reference to the Motor object responsible for the event. This object can be used to find out more
	 * information about the event, although keep in mind the tachometer will likely be changing real-time. To get the
	 * tachometer reading at the time of the event, use getTachoCount().
	 * @return
	 */
	public TachoMotor getMotor() {
		return this.motor;
	}
}
